services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-fastapi:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "run_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - my-network

networks:
  my-network:
    external: true