name: CI - Test and Build Images

on:
  push:
    branches: [Aqill's]
  pull_request:

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest                       
          pip install -r services/preprocessor/requirements.txt
          pip install -r services/trainer/requirements.txt

      - name: Run tests
        run: pytest src/testing/test_pipeline_ci.py

  # docker-build-and-push:
  #   name: Build & Push Docker Images to GHCR
  #   runs-on: ubuntu-latest
  #   needs: test 

  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push trainer image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./services/trainer
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/trainer:latest

  #     - name: Build and push scraper image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./services/scraper
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/scraper:latest

  #     - name: Build and push preprocessor image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./services/preprocessor
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/preprocessor:latest

  #     - name: Build and push web image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./services/web
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/web:latest
