name: Monthly DVC Pipeline

on:
  schedule:
    - cron: '0 3 1 * *'  # Tanggal 1 setiap bulan
  workflow_dispatch:

jobs:
  dvc-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install dvc[gs]  # ganti sesuai remote kamu
          pip install -r requirements.txt

      - name: Configure DVC remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          dvc remote modify minio access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify minio secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Pull data & model
        run: dvc pull -r minio

      - name: Run DVC pipeline
        run: dvc repro
